name: Run Nightly ETL

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every night at 4 AM UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlalchemy pg8000 pandas

    - name: Run test connection
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python test_connection.py
