name: Minimal ETL Test

on:
  workflow_dispatch:  # Trigger manually

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install psycopg2-binary

    - name: Run connection test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python test_connection.py
